# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-05-17 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190517_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='title',
            field=models.CharField(default='new title', max_length=240),
            preserve_default=False,
        ),
    ]
