# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-05-17 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190517_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='title',
            field=models.CharField(error_messages={'blank': 'This field can not be blank', 'unique': 'Ayni baslikta baska kayit olamaz'}, help_text='Must be unique title', max_length=240, unique=True, verbose_name='Post Title'),
        ),
    ]
